#include "mainwindow.h"
#include "batchview.h"
#include <QApplication>

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);

    QCoreApplication::setApplicationName("Yafdb-Validator");
    QCoreApplication::setApplicationVersion("0.1");

    QCommandLineParser parser;
    parser.setApplicationDescription("Yafdb-Validator");
    parser.addHelpOption();
    parser.addVersionOption();
    parser.addPositionalArgument("sourceimage", QCoreApplication::translate("main", "Source image"));
    parser.addPositionalArgument("detectoryml", QCoreApplication::translate("main", "YML generated by the detector"));
    parser.addPositionalArgument("destyml",     QCoreApplication::translate("main", "Destination YML"));

    // Process the actual command line arguments given by the user
    parser.process(app);

    QStringList args = parser.positionalArguments();
    // source is args.at(0), destination is args.at(1)

    if( args.length() < 3 )
    {
        parser.showHelp();
        exit( 0 );
    }

    MainWindow w(0, args);
    w.show();

    return app.exec();
}
