#include "mainwindow.h"
#include "batchview.h"
#include <QApplication>

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);

    QCoreApplication::setApplicationName("Yafdb-Validator");
    QCoreApplication::setApplicationVersion("0.1");

    QCommandLineParser parser;
    parser.setApplicationDescription("Yafdb-Validator");
    parser.addHelpOption();
    parser.addVersionOption();
    parser.addPositionalArgument("sourceimage", QCoreApplication::translate("main", "Source image"));
    parser.addPositionalArgument("detectoryml", QCoreApplication::translate("main", "YML generated by the detector"));
    parser.addPositionalArgument("destyml",     QCoreApplication::translate("main", "Destination YML"));

    // Process the actual command line arguments given by the user
    parser.process(app);

    QStringList args = parser.positionalArguments();
    // source is args.at(0), destination is args.at(1)

    args.append( "/home/f0x/Bureau/Photo_RMLL_2014_panoramique,_WE_grand_public.jpeg" );
    args.append( "/home/f0x/Bureau/Photo_RMLL_2014_panoramique,_WE_grand_public.yml" );
    args.append( "/home/f0x/Bureau/Photo_RMLL_2014_panoramique,_WE_grand_public_new.yml" );

    MainWindow w(0, args);
    w.show();

    return app.exec();
}
